### ISSUE TITLE
这个主题和nexmoe

### ISSUE THREAD

**Issue by zard-zhang** [ch1ny/kira-hexo#1]

**Comment by zard-zhang** [comment]
感觉好像啊

**Comment by ch1ny** [comment]
> 感觉好像啊

是的，因为我最开始用的就是 `nexmoe` ，用的过程中想根据自己做的定制，也模仿 `nexmoe` 的风格做出类似的主题出来。主要是为了方便自己使用以及作为学习 hexo 主题开发的练手。🤪
