### ISSUE TITLE
post.ejs好像有点错误呀

### ISSUE THREAD

**Issue by JIANG54864** [ch1ny/kira-hexo#10]
![image](https://user-images.githubusercontent.com/90563386/219946593-7dc9ca81-4c2e-467e-8412-9367933c9254.png)

**Comment by ch1ny** [comment]
这个是 hexo 提供的 API ，是不是文章没放在 `_posts` 下面？

**Comment by JIANG54864** [comment]
> 这个是 hexo 提供的 API ，是不是文章没放在 `_posts` 下面？

还真是，之前试验page格式建了个文件夹没删，删了就没事了，谢谢学长
