### ISSUE TITLE
部署在 github.io 的子目录中时，css库和js库都会加载失败

### ISSUE THREAD

**Issue by yohoj** [ch1ny/kira-hexo#32]
![image](https://user-images.githubusercontent.com/10977137/227508196-27e554ba-d73a-40ab-9ef5-3cc30cdc2a0c.png)
![image](https://user-images.githubusercontent.com/10977137/227508245-b24e2696-8b52-4700-af4c-96c89c8eda4e.png)
看代码需要将/lib/iconfont/iconfont.css 改成 ./lib/iconfont/iconfont.css

**Comment by ch1ny** [comment]
#33 
不应该改成 `./`，如果部署在子目录下，请更新至 `1.4.1` 后在 `config.yml` 中配置 `root` ，[网址配置 | Hexo](https://hexo.io/zh-cn/docs/configuration#%E7%BD%91%E5%9D%80)
