### ISSUE TITLE
在github pages上面发布后，无法加载layout.css等若干文件

### ISSUE THREAD

**Issue by NShinobu** [ch1ny/kira-hexo#34]
在github pages上面发布后，无法加载layout.css等若干文件，导致网站布局出现问题
![截屏2023-05-19 21 25 33](https://github.com/ch1ny/kira-hexo/assets/122255145/a6da30d3-0271-4aeb-9f86-cde38e495923)

**Comment by ch1ny** [comment]
`config.yml` 文件中设置了 `root` 为 `n-shinobu`，把这个去掉

**Comment by NShinobu** [comment]
感谢！经过排查发现是url设置错了，应该是url: 'https://nshinobu.github.io/'
