### ISSUE TITLE
非常感谢作者！！！Ciallo～(∠・ω< )⌒★

### ISSUE THREAD

**Issue by kalipolis** [ch1ny/kira-hexo#38]
这个主题集成的插件太好用了，个人感觉比next更适合我的需求！根据作者的模板，我也成功搭建了自己的[个人博客](https://kalipolis.gitee.io)，现在基本没有bug，就是使用您集成的gitalk插件时，第一个帖子没有办法评论，再次感谢作者，话说我们的兴趣爱好真是基本一样呢

**Comment by adolphshi** [comment]
Ciallo～(∠・ω< )⌒★
