### ISSUE TITLE
更改背景

### ISSUE THREAD

**Issue by Tioz** [ch1ny/kira-hexo#39]
![屏幕截图 2023-11-22 224007](https://github.com/ch1ny/kira-hexo/assets/111218489/46a4893c-234a-46c9-8084-f59fc3b47354)
![屏幕截图 2023-11-22 224051](https://github.com/ch1ny/kira-hexo/assets/111218489/b9280b49-5567-4bda-befc-82fa74e6c58d)
为什么我更改背景了，但是显示不出来呢

**Comment by ch1ny** [comment]
因为你填的这个链接是 Github 仓库里这个图片的页面，你需要换成这个 `https://raw.githubusercontent.com/Tioz/Picture/main/1.jpg`

**Comment by Tioz** [comment]
原来如此，感谢
