### ISSUE TITLE
代码块复制

### ISSUE THREAD

**Issue by Tioz** [ch1ny/kira-hexo#40]
![image](https://github.com/ch1ny/kira-hexo/assets/111218489/d5d99ea6-32d3-4dc4-8350-b0e7b26d95a2)
这是你的blog里面的画面

![image](https://github.com/ch1ny/kira-hexo/assets/111218489/d9b9cf19-622b-4bdd-ae44-f5090f293190)
这是我的blog里面的

代码块复制也是打开的
![image](https://github.com/ch1ny/kira-hexo/assets/111218489/e06ad23b-67ef-4f28-9c70-d5512de945ac)
但是不知道为什么就是不能复制

**Comment by ch1ny** [comment]
https://hexo.kira.host/faqs.html

代码块高亮是否有开启？

**Comment by ch1ny** [comment]
有点神奇，能不能提供一个可以复现的临时 demo ？

如果提供 demo 比较麻烦的话，可以试试通过 `pnpm create kira-hexo myblog` 创建一个默认的博客模板，把自己的文章和配置替换进去。

https://hexo.kira.host/#%E4%BD%BF%E7%94%A8%E6%A8%A1%E6%9D%BF

![image](https://github.com/ch1ny/kira-hexo/assets/57794772/e31969f6-807a-4684-8c49-f1e975b8a0dd)

**Comment by ch1ny** [comment]
啊我应该知道了，你的博客部署在 github io 的子页面了，我看看是不是我的代码没做这个的兼容

**Comment by ch1ny** [comment]
> 啊我应该知道了，你的博客部署在 github io 的子页面了，我看看是不是我的代码没做这个的兼容

代码块复制这个地方没有做兼容处理，我修复一下发个新版本

**Comment by ch1ny** [comment]
这个 bug 已经修复了，升级到 "hexo-theme-kira": "^1.4.5" 就可以了。
感谢反馈~

**Comment by Tioz** [comment]
我能问一下怎么更新吗
![05865556](https://github.com/ch1ny/kira-hexo/assets/111218489/8868029a-c966-4284-b0bb-ef4cc680a293)

**Comment by Tioz** [comment]
啊找到了方法了，感谢
