### ISSUE TITLE
播放器不能播放vip音乐 有没有办法携带cookie播放？ 感谢！

### ISSUE THREAD

**Issue by kyui-azusa** [ch1ny/kira-hexo#43]

**Comment by ch1ny** [comment]
kira-hexo 的音乐播放器基于 Aplayer 和 metingJS 实现，我不关心它们的内部逻辑，可以到对应项目下提 issue 询问。

个人理解应该是不行的，即使技术上可行也存在版权问题，可能有法律风险。
