### ISSUE TITLE
评论是不是寄了

### ISSUE THREAD

**Issue by adolphshi** [ch1ny/kira-hexo#45]
![Screenshot 2024-01-09 at 14-54-28 关于本人 - adolphshi的小窝](https://github.com/ch1ny/kira-hexo/assets/121488030/7358548f-ccfa-4eb0-81ab-b7eae69d5112)
显示不出来

**Comment by ch1ny** [comment]
![image](https://github.com/ch1ny/kira-hexo/assets/57794772/a6cffe24-957f-49f2-9ca4-e91af14e6e8d)
你这个咋读的我的仓库下的 discussions ？是不是没有把 giscus 的配置改成你自己的仓库的？
